Repository OpenCoreMMO/OpenCoreMMO, pull requests merged in 2025-01, with the labels that each got.

#642 Feature: Global Events
  data/LuaJit/README.md
  data/LuaJit/libs/core/game.lua
  data/LuaJit/libs/core/load.lua
  data/LuaJit/libs/functions/revscriptsys.lua
  data/LuaJit/scripts/globalevents/example_save.lua
  data/LuaJit/scripts/globalevents/example_shutdown.lua
  data/LuaJit/scripts/globalevents/example_startup.lua
  data/LuaJit/scripts/globalevents/example_think.lua
  data/LuaJit/scripts/globalevents/online_record.lua
  data/LuaJit/scripts/talkactions/player/test.lua
  src/ApplicationServer/NeoServer.Server.Commands/Player/PlayerLogInCommand.cs
  src/ApplicationServer/NeoServer.Server.Contracts/Contracts/IGameCreatureManager.cs
  src/ApplicationServer/NeoServer.Server.Contracts/Contracts/Scripts/IScriptGameManager.cs
  src/ApplicationServer/NeoServer.Server.Contracts/Contracts/Tasks/IDispatcher.cs
  src/ApplicationServer/NeoServer.Server.Contracts/Contracts/Tasks/IScheduler.cs
  src/ApplicationServer/NeoServer.Server.Routines/Persistence/PlayerPersistenceRoutine.cs
  src/ApplicationServer/NeoServer.Server/Managers/GameCreatureManager.cs
  src/ApplicationServer/NeoServer.Server/Tasks/Dispatcher.cs
  src/ApplicationServer/NeoServer.Server/Tasks/Scheduler.cs
  src/Database/NeoServer.Data/Configurations/ForSqLite/ForSqLiteWorldRecordEntityConfiguration.cs
  src/Database/NeoServer.Data/Configurations/WorldRecordEntityConfiguration.cs
  src/Database/NeoServer.Data/Contexts/NeoContext.cs
  src/Database/NeoServer.Data/Entities/WorldEntity.cs
  src/Database/NeoServer.Data/Entities/WorldRecordEntity.cs
  src/Database/NeoServer.Data/Interfaces/IWorldRecordRepository.cs
  src/Database/NeoServer.Data/Repositories/WorldRecordRepository.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/Enums/LuaDefinitions.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/Functions/GameFunctions.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/Functions/GlobalEventFunctions.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/Functions/GlobalFunctions.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/Functions/Interfaces/IGlobalEventFunctions.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/GlobalEvent.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/GlobalEvents.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/Interfaces/IGlobalEvents.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/Interfaces/ILuaEnvironment.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/IoC/Modules/LuaJITInjection.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/LuaEnvironment.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/LuaScriptGameManager.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/LuaStartup.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/TalkAction.cs
  src/GameWorldSimulator/NeoServer.Game.Common/Contracts/Creatures/IPlayer.cs
  src/GameWorldSimulator/NeoServer.Game.Creatures/Player/Player.cs
  src/Loaders/NeoServer.Loaders/Players/PlayerLoader.cs
  src/Shared/NeoServer.IoC/Modules/DatabaseInjection.cs
  src/Standalone/Program.cs
  tests/NeoServer.Game.Tests/Server/GameServerTestBuilder.cs
Labels: enhancement

#651 Feature: database functions
  data/LuaJit/README.md
  data/LuaJit/scripts/talkactions/player/test.lua
  src/Database/NeoServer.Data/Configurations/AccountEntityConfiguration.cs
  src/Database/NeoServer.Data/Configurations/AccountVipListEntityConfiguration.cs
  src/Database/NeoServer.Data/Configurations/ForSqLite/ForSqLiteAccountEntityConfiguration.cs
  src/Database/NeoServer.Data/Configurations/ForSqLite/ForSqLiteGuildEntityConfiguration.cs
  src/Database/NeoServer.Data/Configurations/ForSqLite/ForSqLiteGuildRankEntityConfiguration.cs
  src/Database/NeoServer.Data/Configurations/ForSqLite/ForSqLiteWorldEntityConfiguration.cs
  src/Database/NeoServer.Data/Configurations/ForSqLite/ForSqLiteWorldRecordEntityConfiguration.cs
  src/Database/NeoServer.Data/Configurations/GuildEntityConfiguration.cs
  src/Database/NeoServer.Data/Configurations/GuildMembershipEntityConfiguration.cs
  src/Database/NeoServer.Data/Configurations/GuildRankEntityConfiguration.cs
  src/Database/NeoServer.Data/Configurations/PlayerOutfitAddonEntityConfiguration.cs
  src/Database/NeoServer.Data/Configurations/PlayerQuestEntityConfiguration.cs
  src/Database/NeoServer.Data/Configurations/PlayerStorageEntityConfiguration.cs
  src/Database/NeoServer.Data/Configurations/WorldEntityConfiguration.cs
  src/Database/NeoServer.Data/Configurations/WorldRecordEntityConfiguration.cs
  src/Database/NeoServer.Data/Contexts/NeoContext.cs
  src/Database/NeoServer.Data/Extensions/StringExtensions.cs
  src/Database/NeoServer.Data/Helpers/DBResult.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/Extensions/BitArrayExtensions.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/Functions/DBFunctions.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/Functions/Interfaces/IDBFunctions.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/Functions/Interfaces/IResultFunctions.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/Functions/ResultFunctions.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/IoC/Modules/LuaJITInjection.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/LuaStartup.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/ScriptEnvironment.cs
Labels: enhancement

#652 Feature: database functions
  data/LuaJit/README.md
  data/LuaJit/scripts/creaturescripts/others/onthink_example.lua
  data/LuaJit/scripts/creaturescripts/player/login.lua
  data/LuaJit/scripts/talkactions/player/test.lua
  src/Database/NeoServer.Data/Configurations/AccountEntityConfiguration.cs
  src/Database/NeoServer.Data/Configurations/AccountVipListEntityConfiguration.cs
  src/Database/NeoServer.Data/Configurations/ForSqLite/ForSqLiteAccountEntityConfiguration.cs
  src/Database/NeoServer.Data/Configurations/ForSqLite/ForSqLiteGuildEntityConfiguration.cs
  src/Database/NeoServer.Data/Configurations/ForSqLite/ForSqLiteGuildRankEntityConfiguration.cs
  src/Database/NeoServer.Data/Configurations/ForSqLite/ForSqLiteWorldEntityConfiguration.cs
  src/Database/NeoServer.Data/Configurations/ForSqLite/ForSqLiteWorldRecordEntityConfiguration.cs
  src/Database/NeoServer.Data/Configurations/GuildEntityConfiguration.cs
  src/Database/NeoServer.Data/Configurations/GuildMembershipEntityConfiguration.cs
  src/Database/NeoServer.Data/Configurations/GuildRankEntityConfiguration.cs
  src/Database/NeoServer.Data/Configurations/PlayerOutfitAddonEntityConfiguration.cs
  src/Database/NeoServer.Data/Configurations/PlayerQuestEntityConfiguration.cs
  src/Database/NeoServer.Data/Configurations/PlayerStorageEntityConfiguration.cs
  src/Database/NeoServer.Data/Configurations/WorldEntityConfiguration.cs
  src/Database/NeoServer.Data/Configurations/WorldRecordEntityConfiguration.cs
  src/Database/NeoServer.Data/Contexts/NeoContext.cs
  src/Database/NeoServer.Data/Extensions/StringExtensions.cs
  src/Database/NeoServer.Data/Helpers/DBResult.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/Extensions/BitArrayExtensions.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/Functions/DBFunctions.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/Functions/Interfaces/IDBFunctions.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/Functions/Interfaces/IResultFunctions.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/Functions/ResultFunctions.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/IoC/Modules/LuaJITInjection.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/LuaStartup.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/ScriptEnvironment.cs
  src/GameWorldSimulator/NeoServer.Game.Creatures/Models/Bases/CombatActor.cs
Labels: enhancement

#664 feat: add world module.
  src/Database/NeoServer.Data/Configurations/WorldEntityConfiguration.cs
  src/Database/NeoServer.Data/Entities/WorldEntity.cs
  src/Database/NeoServer.Data/Interfaces/IWorldRepository.cs
  src/Database/NeoServer.Data/Repositories/WorldRepository.cs
  src/Database/NeoServer.Data/Seeds/WorldModelSeed.cs
  src/Shared/NeoServer.IoC/Modules/DatabaseInjection.cs
  src/WebAPI/Application/UseCases/Commands/CreateWorldCommand.cs
  src/WebAPI/Application/UseCases/Commands/DeleteWorldCommand.cs
  src/WebAPI/Application/UseCases/Queries/GetWorldByIdQuery.cs
  src/WebAPI/Application/UseCases/Queries/GetWorldsQuery.cs
  src/WebAPI/AutoMapperProfiles/WorldProfile.cs
  src/WebAPI/Controllers/WorldController.cs
  src/WebAPI/Program.cs
  src/WebAPI/Requests/Commands/CreateWorldRequest.cs
  src/WebAPI/Requests/Commands/DeleteWorldCommandRequest.cs
  src/WebAPI/Requests/Queries/GetWorldByIdRequest.cs
  src/WebAPI/Requests/Queries/GetWorldsRequest.cs
  src/WebAPI/Requests/Validators/CreateWorldValidator.cs
  src/WebAPI/Response/Constants/ConstantMessage.cs
  src/WebAPI/Response/World/WorldResponseViewModel.cs
  src/WebAPI/Swagger/SchemaFilters/EnumSchemaFilter.cs
  tests/NeoServer.WebApi.Tests/NeoServer.WebApi.Tests.csproj
  tests/NeoServer.WebApi.Tests/Tests/WorldTests.cs
Labels: enhancement, administrator

#666 feat:create game logic to validate if account or ip was banished.
  src/Database/NeoServer.Data/Interfaces/IIpBansRepository.cs
  src/Database/NeoServer.Data/Repositories/IpBansRepository.cs
  src/NetworkingServer/NeoServer.Networking.Handlers/LogIn/AccountLoginHandler.cs
  src/NetworkingServer/NeoServer.Networking.Handlers/LogIn/PlayerLogInHandler.cs
  src/WebAPI/Application/UseCases/Commands/BanIpCommand.cs
  src/WebAPI/Application/UseCases/Queries/GetIpBanByIpQuery.cs
Labels: enhancement, anti-cheat
