Repository OpenCoreMMO/OpenCoreMMO, pull requests merged in 2025-07, with the labels that each got.

#726 feat: add news rune attack spells.
  data/scripts/runes/attack/explosion.lua
  data/scripts/runes/attack/fireball.lua
  data/scripts/runes/attack/great_fireball.lua
  data/scripts/runes/attack/icicle.lua
Labels: enhancement, core

#727 feat: add news runes attack.
  data/scripts/runes/attack/stalagmite.lua
  data/scripts/runes/attack/stone_shower.lua
  data/scripts/runes/attack/thunderstorm.lua
Labels: enhancement, core

#746 feat: is corpses function
  src/Core/NeoServer.Domain/Common/Contracts/Items/IItemType.cs
  src/Core/NeoServer.Domain/Common/Item/ItemAttribute.cs
  src/Core/NeoServer.Domain/Items/ItemType.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/Extensions/ItemAttributeTypeExtensions.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/Functions/ItemTypeFunctions.cs
  src/Loaders/NeoServer.Loaders/OTB/Parsers/ItemAttributeTranslationMap.cs
Labels: enhancement

#751 feat: functions get top down and get top top items
  src/ApplicationServer/NeoServer.Server.Commands/Movements/ToContainer/MapToContainerMovementOperation.cs
  src/ApplicationServer/NeoServer.Server.Commands/Movements/ToInventory/MapToInventoryMovementOperation.cs
  src/ApplicationServer/NeoServer.Server.Commands/Player/UseItem/ItemFinder.cs
  src/ApplicationServer/NeoServer.Server.Commands/Player/UseItem/PlayerUseItemOnCreatureCommand.cs
  src/ApplicationServer/NeoServer.Server.Commands/Trade/TradeRequestCommand.cs
  src/Core/NeoServer.Domain/Common/Contracts/World/Tiles/ITile.cs
  src/Core/NeoServer.Domain/Creatures/Player/Player.cs
  src/Core/NeoServer.Domain/Creatures/Player/PlayerHand.cs
  src/Core/NeoServer.Domain/Items/Factories/ItemFactory.cs
  src/Core/NeoServer.Domain/Items/ItemType.cs
  src/Core/NeoServer.Domain/World/Algorithms/TileDestinationCalculation.cs
  src/Core/NeoServer.Domain/World/Models/Tiles/BaseTile.cs
  src/Core/NeoServer.Domain/World/Models/Tiles/DynamicTile.cs
  src/Core/NeoServer.Domain/World/Models/Tiles/StaticTile.cs
  src/Core/NeoServer.Domain/World/Services/ToMapMovementService.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/Functions/ItemFunctions.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/Functions/TileFunctions.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/ScriptServices/LuaActionScriptService.cs
  tests/NeoServer.Domain.Tests/Creature/Players/PlayerMoveItemTests.cs
  tests/NeoServer.Domain.Tests/Items/Items/Attributes/DecayableTests.cs
  tests/NeoServer.Domain.Tests/Systems/SafeTrade/TradeCompletionTests.cs
  tests/NeoServer.Domain.Tests/World/TileHeightTests.cs
  tests/NeoServer.Domain.Tests/World/TileTest.cs
Labels: enhancement

#752 feat: custom attributes
  data/extensions/Items/Doors/Door.cs
  data/extensions/Items/Doors/LevelDoor.cs
  data/extensions/Items/Lever.cs
  src/ApplicationServer/NeoServer.Server.Commands/Player/UseItem/PlayerOpenDepotCommand.cs
  src/ApplicationServer/NeoServer.Server/Managers/GameCreatureManager.cs
  src/Core/NeoServer.Domain/Common/Contracts/Creatures/ICreature.cs
  src/Core/NeoServer.Domain/Common/Contracts/Creatures/INpc.cs
  src/Core/NeoServer.Domain/Common/Contracts/Creatures/ISummon.cs
  src/Core/NeoServer.Domain/Common/Contracts/Items/IItemFactory.cs
  src/Core/NeoServer.Domain/Creatures/Events/Player/PlayerOpenedContainerEventHandler.cs
  src/Core/NeoServer.Domain/Creatures/Models/Bases/CombatActor.cs
  src/Core/NeoServer.Domain/Creatures/Models/Bases/Creature.cs
  src/Core/NeoServer.Domain/Creatures/Monster/Monster.cs
  src/Core/NeoServer.Domain/Creatures/Monster/Summon/Summon.cs
  src/Core/NeoServer.Domain/Creatures/Player/Player.cs
  src/Core/NeoServer.Domain/Creatures/Services/DealTransaction.cs
  src/Core/NeoServer.Domain/Items/BaseAttributeList.cs
  src/Core/NeoServer.Domain/Items/Events/FieldRuneUsedEventHandler.cs
  src/Core/NeoServer.Domain/Items/Factories/ItemFactory.cs
  src/Core/NeoServer.Domain/Items/Items/UsableItems/Runes/Rune.cs
  src/Core/NeoServer.Domain/Items/Items/Weapons/ThrowableWeapon.cs
  src/Core/NeoServer.Domain/Services/PlayerUseService.cs
  src/Database/NeoServer.Data/Configurations/ForSqLite/ForSqLitePlayerDepotItemEntityConfiguration.cs
  src/Database/NeoServer.Data/Configurations/ForSqLite/ForSqLitePlayerInventoryItemEntityConfiguration.cs
  src/Database/NeoServer.Data/Configurations/ForSqLite/ForSqLitePlayerItemEntityConfiguration.cs
  src/Database/NeoServer.Data/Configurations/PlayerDepotItemEntitytConfiguration.cs
  src/Database/NeoServer.Data/Configurations/PlayerInventoryItemEntityConfiguration.cs
  src/Database/NeoServer.Data/Configurations/PlayerItemEntityConfiguration.cs
  src/Database/NeoServer.Data/Entities/PlayerInventoryItemEntity.cs
  src/Database/NeoServer.Data/Entities/PlayerItemBaseEntity.cs
  src/Database/NeoServer.Data/Extensions/JsonExtensions.cs
  src/Database/NeoServer.Data/Extensions/PlayerItemModelExtensions.cs
  src/Database/NeoServer.Data/NeoServer.Data.csproj
  src/Database/NeoServer.Data/Parsers/ItemEntityParser.cs
  src/Database/NeoServer.Data/Repositories/Player/ContainerManager.cs
  src/Database/NeoServer.Data/Repositories/Player/InventoryManager.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/Enums/LuaDefinitions.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/Functions/CreatureFunctions.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/Functions/ItemFunctions.cs
  src/Loaders/NeoServer.Loaders/NeoServer.Loaders.csproj
  src/Loaders/NeoServer.Loaders/Players/PlayerLoader.cs
  src/Loaders/NeoServer.Loaders/World/WorldLoader.cs
  tests/NeoServer.Domain.Tests/Creature/Services/DealTransactionTest.cs
Labels: enhancement

#760 fix: cumulative items amount
  src/Core/NeoServer.Domain/Common/Contracts/Items/Types/ICumulative.cs
  src/Core/NeoServer.Domain/Items/Bases/CumulativeEquipment.cs
  src/Core/NeoServer.Domain/Items/Factories/ItemFactory.cs
  src/Core/NeoServer.Domain/Items/Items/Cumulatives/Cumulative.cs
  src/Database/NeoServer.Data/Parsers/ItemEntityParser.cs
Labels: enhancement

#767 feature: lua script auto reload
  src/ApplicationServer/NeoServer.Server/Configurations/ServerConfiguration.cs
  src/Core/NeoServer.Domain/Common/ReloadType.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/Enums/ConfigDefinitions.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/Functions/EnumFunctions.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/Functions/GameFunctions.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/Interfaces/IReloadManager.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/IoC/Modules/LuaJITInjection.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/LuaFunctionsLoader.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/LuaScriptManager.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/LuaStartup.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/ReloadManager.cs
  src/Standalone/IoC/Modules/ConfigurationInjection.cs
  src/Standalone/appsettings.Local.json
  src/Standalone/appsettings.json
  tests/NeoServer.Domain.Tests/Server/ScriptManagerTestBuilder.cs
Labels: enhancement

#770 fix: removed cached creatures from dynamic tile cache
  src/Core/NeoServer.Domain/World/Models/Tiles/DynamicTile.cs
Labels: enhancement

#771 fix: old player instance on map after dead
  src/ApplicationServer/NeoServer.Server.Events/Creature/CreatureDeathEventHandler.cs
  src/Core/NeoServer.Domain/Common/Contracts/Creatures/IPlayer.cs
  src/Core/NeoServer.Domain/Creatures/Player/Player.cs
  tests/NeoServer.Domain.Tests/Creature/Creature/PlayerTest.cs
Labels: enhancement

#772 fix: load access from account group, to god see more details on look
  src/Core/NeoServer.Domain/Creatures/Player/Player.cs
Labels: enhancement

#776 fix: looktype ushort
  src/Core/NeoServer.Domain/Creatures/Factories/NpcFactory.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/LuaFunctionsLoader.cs
  src/Loaders/NeoServer.Loaders/Players/PlayerLoader.cs
Labels: enhancement

#777 feat: town functions
  README.md
  data/.vscode/lua/town_functions.lua
  data/scripts/talkactions/gm/down.lua
  data/scripts/talkactions/gm/ghost.lua
  data/scripts/talkactions/gm/goto.lua
  data/scripts/talkactions/gm/teleport_ntiles.lua
  data/scripts/talkactions/gm/teleport_to_town.lua
  data/scripts/talkactions/gm/up.lua
  src/Core/NeoServer.Domain/World/World.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/Functions/Interfaces/ITownFunctions.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/Functions/TownFunctions.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/IoC/Modules/LuaJITInjection.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/LuaScriptGameManager.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/LuaStartup.cs
Labels: documentation, enhancement

#778 feat: event callbacks
  data/.vscode/lua/eventcallback_functions.lua
  data/.vscode/settings.json
  data/libs/functions/revscriptsys.lua
  data/scripts/eventcallbacks/player/on_inventory_update.lua
  data/scripts/eventcallbacks/player/on_storage_update.lua
  data/scripts/eventcallbacks/player/on_think.lua
  data/scripts/eventcallbacks/player/on_walk.lua
  src/Core/NeoServer.Domain/Common/Contracts/Creatures/IPlayer.cs
  src/Core/NeoServer.Domain/Creatures/Events/Player/PlayerInventoryUpdateEvent.cs
  src/Core/NeoServer.Domain/Creatures/Events/Player/PlayerRotateItemEvent.cs
  src/Core/NeoServer.Domain/Creatures/Events/Player/PlayerStorageUpdateEvent.cs
  src/Core/NeoServer.Domain/Creatures/Events/Player/PlayerThinkEvent.cs
  src/Core/NeoServer.Domain/Creatures/Events/Player/PlayerWalkEvent.cs
  src/Core/NeoServer.Domain/Creatures/Player/Player.cs
  src/Core/NeoServer.Domain/Items/Bases/Equipment.cs
  src/Database/NeoServer.Data/Entities/PlayerStorageEntity.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/Enums/LuaDefinitions.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/EventCallback.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/Events/Callbacks/Player/PlayerInventoryUpdateEventEventHandler.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/Events/Callbacks/Player/PlayerRotateItemEventEventHandler.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/Events/Callbacks/Player/PlayerStorageUpdateEventHandler.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/Events/Callbacks/Player/PlayerThinkUpdateEventHandler.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/Events/Callbacks/Player/PlayerWalkEventEventHandler.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/EventsCallbacks.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/Functions/EventCallbackFunctions.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/Functions/GameFunctions.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/Functions/Interfaces/IEventCallbackFunctions.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/Functions/PlayerFunctions.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/Interfaces/IEventsCallbacks.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/IoC/Modules/LuaJITInjection.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/LuaStartup.cs
  src/Extensions/NeoServer.Scripts.LuaJIT/Scripts.cs
  src/Loaders/NeoServer.Loaders/Players/PlayerLoader.cs
  tests/NeoServer.Domain.Tests/Creature/Players/PlayerTests.cs
  tests/NeoServer.Domain.Tests/Helpers/Player/PlayerTestDataBuilder.cs
Labels: enhancement

#779 fix: adjustments in interval and get attribute
  src/ApplicationServer/NeoServer.Server.Routines/Creatures/GameCreatureRoutine.cs
  src/Core/NeoServer.Domain/Items/BaseAttributeList.cs
Labels: bug
